### ISSUE TITLE
Some prescription drugs lack dosage unit or value

### ISSUE THREAD

**Issue by vinceleung87** [ChiragPDave/Rx-Products-API-Call-to-CSV#1]
![image](https://user-images.githubusercontent.com/87508807/125882335-8f19627a-1896-49fd-90c5-92be95777c77.png)

Not all drugs have a listed dosage unit?

**Comment by ChiragPDave** [comment]
@vinceleung87 It looks like some drugs simply had no entry for dosage_unit or dosage_value.  API data [here](https://health-products.canada.ca/api/drug/activeingredient/?lang=en&type=json).

I suppose while a drug's concentration can be determined in mg, it can be administered as mL (i.e. drops).  When there is no dosage_unit/dosage_value, then the drug is administered as it is designed (i.e. the case of a tablet).

Does this help answer the question?
